#!/bin/bash

SHELL_ACTIVE="${HOME}/.$(basename $SHELL)rc"

add_config_rc(){
	if ! grep -qe "^stty stop undef" ${SHELL_ACTIVE} >/dev/null; then
		echo "stty stop undef" >> ${SHELL_ACTIVE}
	fi
	if ! grep -qe "^stty start undef" ${SHELL_ACTIVE} >/dev/null; then
		echo "stty start undef" >> ${SHELL_ACTIVE}
	fi
	if ! grep -qe "^alias smake=supramake" ${SHELL_ACTIVE} >/dev/null; then
		echo "alias smake=supramake" >> ${SHELL_ACTIVE}
	fi
	if ! grep -qe "^alias q=exit" ${SHELL_ACTIVE} >/dev/null; then
		echo "alias q=exit" >> ${SHELL_ACTIVE}
	fi
	if ! grep -qe "^bindkey -s '\^[[][[]15\~' 'supramake run[\\]n'" ${SHELL_ACTIVE} >/dev/null; then
		echo add supramake 1
		echo "bindkey -s '^[[15~' 'supramake run\n'" >> ${SHELL_ACTIVE}
	fi
	if ! grep -qe "^bindkey -s '\^[[][[]17\~' 'supramake run2[\\]n'" ${SHELL_ACTIVE} >/dev/null; then
		echo add supramake 1
		echo "bindkey -s '^[[17~' 'supramake run2\n'" >> ${SHELL_ACTIVE}
	fi
	if ! grep -qe "^bindkey -s '\^[[][[]18\~' 'supramake run3[\\]n'" ${SHELL_ACTIVE} >/dev/null; then
		echo add supramake 1
		echo "bindkey -s '^[[18~' 'supramake run3\n'" >> ${SHELL_ACTIVE}
	fi
	if ! grep -qe "^export fpath=(${HOME}/.local/bin \$fpath)" ${SHELL_ACTIVE} >/dev/null; then
		echo "export fpath=(${HOME}/.local/bin \$fpath)" >> ${SHELL_ACTIVE}
		echo "autoload compinit; compinit" >> ${SHELL_ACTIVE}
	fi

}

add_config_rc
