#!/bin/bash

if ! test -n "$1"; then
	echo "Add cfg argument"
	exit 1
fi

# Init Variable

theme='gruvbox'
mouse=0
swap=0
tree=0
norme=0
nobackground=0
balise=""

# get theme and balise YOUR CONFIG only if .vimrc exist

if [ -e "$HOME/.vimrc" ]; then
	HEAD=$(head $HOME/.vimrc -n 20)
	balise_len="`grep -Eoz "#[=]+.+" $HOME/.vimrc 2>/dev/null | wc -l`"
	balise="`tail -n$(($balise_len - 1)) $HOME/.vimrc | head -n$((balise_len - 2))`"
	theme=$(grep colorscheme ~/.vimrc | grep -Eo "[a-z]+$")
else
	mouse=1
	swap=1
	tree=1
fi

# set to true if options is true in .vimrc

if echo "$HEAD" | grep -q "g:sp_mouse = true"; then
	mouse=1
fi
if echo "$HEAD" | grep -q "g:sp_swap = true"; then
	swap=1
fi
if echo "$HEAD" | grep -q "g:sp_tree = true"; then
	tree=1
fi
if echo "$HEAD" | grep -q "g:sp_norme = true"; then
	norme=1
fi
if echo "$HEAD" | grep -q "g:sp_nobackground = true"; then
	nobackground=1
fi



echo "sv_mouse:$mouse" > $1
echo "sv_swap:$swap" >> $1
echo "sv_tree:$tree" >> $1
echo "sv_nobackground:$nobackground" >> $1
echo "sv_theme:$theme" >> $1
echo "sv_norme:$norme" >> $1
echo "sv_perso_conf:" >> $1
echo "$balise" >> $1

# echo "$HEAD"
