#!/bin/bash

if command -v clangd &>/dev/null; then
	clangd "-j" "8" "$@"
	exit $?
fi

if command -v ccls &>/dev/null; then
	ccls --init="{\"cache\": {\"directory\": \"/tmp/ccls-cache_$USER\"}}" "$@"
	exit $?
fi

exit 42
